### ISSUE TITLE
random documentation incompletenesses

### ISSUE THREAD

**Issue by ottaviadipasquale** [ottaviadipasquale/react-fmri#3]
- [x] The link to Pypi is broken
- [x] The `url` in `setup.py` is missing
- [x] The installation instructions are misleading (for conda, one does not need to install the requirements)
- [x] The minimum numpy version should be 1.14 (nibabel requires it)

**Comment by matteofrigo** [comment]
Commit a02c6d61c3069b2959a0fcf34ada56d26ddc2054 fixes the Pypi link

**Comment by matteofrigo** [comment]
Commit 35cc0550b8347f59c83743e57abf854f3f2bf36d fixes the url in setup.py

**Comment by matteofrigo** [comment]
Commit 83d13f5f06f799c49a76327946a23aa6eecf255f improves installation instructions and fixes the minimum required version of each package
