### ISSUE TITLE
error message 'FileNotFoundError' when running react_masks

### ISSUE THREAD

**Issue by MaraCerci** [ottaviadipasquale/react-fmri#5]
Hello
I had the following error message when running react_masks:

Traceback (most recent call last):
  File "/home/sapmc4/.local/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by ottaviadipasquale** [comment]
Hello,

Please make sure that there are no empty lines within the txt file reporting the subjects' data (i.e. subject_list).

Ottavia
